---
- name: centos | installing keepalived
  yum:
    name: keepalived
    state: present

- name: centos | enabling keepalived on boot and start
  service:
    name: keepalived
    state: started
    enabled: yes

- name: centos | allowing VIP to come up on both nodes
  sysctl:
    name: "net.ipv4.ip_nonlocal_bind"
    value: 1
    state: present
    reload: yes

- name: centos | configuring keepalived
  template:
    src: "etc/keepalived/keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart keepalived
