---
# Only used if using GlusterFS back-end. Will more than likely be removed over time
- name: config_keepalived | mounting gluster volumes - scripts
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }}"
    state: mounted
  with_items:
    - mountpoint: '{{ scripts_home }}'
      src: '{{ primary_gfs_server }}:/{{ keepalived_scripts_mnt }}'
      fstype: 'glusterfs'
      options: 'defaults,_netdev,backupvolfile-server={{ secondary_gfs_server }}'

- name: config_keepalived | copying keepalived scripts
  template:
    src: "opt/scripts/{{ item.src }}"
    dest: "{{ scripts_home }}/{{ item.dest }}"
    owner: root
    group: root
    mode: 0774
  with_items:
    - src: backup.sh.j2
      dest: backup.sh
    - src: fault.sh.j2
      dest: fault.sh
    - src: master.sh.j2
      dest: master.sh
    - src: primary-backup.sh.j2
      dest: primary-backup.sh
  notify: restart keepalived
  run_once: true
